### ISSUE TITLE
Protocol error (Target.createTarget) with Chrome or Brave 96

### ISSUE THREAD

**Issue by brauliobo** [YusukeIwaki/puppeteer-ruby#169]
### Step To Reproduce / Observed behavior
Using the following code:
```ruby
require 'puppeteer-ruby'

options = {
  headless: false,
  devtools: true,
  slow_mo:  50,
  args: ['--guest', '--window-size=1280,800'],
}

Puppeteer.launch **options do |browser|
  page = browser.new_page
  require'pry';binding.pry

  url = 'https://kernel.org'
  page.goto(url, wait_until: 'domcontentloaded')
  require'pry';binding.pry
end
```

I always get:
```
➜  reading-group-bot git:(master) ✗ be ruby documents.rb
/home/braulio/.rvm/gems/ruby-3.0.3/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/promises.rb:1257:in `raise': Protocol error (Target.createTarget): Failed to open a new tab (Puppeteer::Connection::ProtocolError)
        from /home/braulio/.rvm/gems/ruby-3.0.3/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/promises.rb:1257:in `wait_until_resolved!'
        from /home/braulio/.rvm/gems/ruby-3.0.3/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/promises.rb:1471:in `value!'
        from /home/braulio/.rvm/gems/ruby-3.0.3/gems/puppeteer-ruby-0.37.2/lib/puppeteer/concurrent_ruby_utils.rb:54:in `await'
        from /home/braulio/.rvm/gems/ruby-3.0.3/gems/puppeteer-ruby-0.37.2/lib/puppeteer/connection.rb:129:in `send_message'
        from /home/braulio/.rvm/gems/ruby-3.0.3/gems/puppeteer-ruby-0.37.2/lib/puppeteer/browser.rb:190:in `create_page_in_context'
        from /home/braulio/.rvm/gems/ruby-3.0.3/gems/puppeteer-ruby-0.37.2/lib/puppeteer/browser_context.rb:106:in `new_page'
        from /home/braulio/.rvm/gems/ruby-3.0.3/gems/puppeteer-ruby-0.37.2/lib/puppeteer/browser.rb:180:in `new_page'
        from documents.rb:11:in `block in <main>'
        from /home/braulio/.rvm/gems/ruby-3.0.3/gems/puppeteer-ruby-0.37.2/lib/puppeteer/puppeteer.rb:79:in `launch'
        from /home/braulio/.rvm/gems/ruby-3.0.3/gems/puppeteer-ruby-0.37.2/lib/puppeteer.rb:80:in `public_send'
        from /home/braulio/.rvm/gems/ruby-3.0.3/gems/puppeteer-ruby-0.37.2/lib/puppeteer.rb:80:in `block (3 levels) in <module:Puppeteer>'
        from documents.rb:10:in `<main>'
```

### Expected behavior
Not to error

### Environment
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]

**Comment by brauliobo** [comment]
Removing `args: ['--guest', '--window-size=1280,800']` option make it work. This option should be removed from the documentation.

**Comment by YusukeIwaki** [comment]
Hi, thank you for the kind reporting :)
I will modify the docs.

By the way, this issue is also reproduced in original JS version of Puppeteer, and I posted a report for it: https://github.com/puppeteer/puppeteer/issues/7807
I will check it for confirming whether this issue is just a limitation or a bug.
