### ISSUE TITLE
browser.disconnect caused IOError

### ISSUE THREAD

**Issue by dexterouschen** [YusukeIwaki/puppeteer-ruby#337]
### Step To Reproduce / Observed behavior

```
browser_ws_endpoint = 'ws://127.0.0.1:9222/devtools/browser/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
browser = Puppeteer.connect(
  browser_ws_endpoint:,
  default_viewport: Puppeteer::Viewport.new(width: 1280, height: 800)
)
page = browser.new_page
page.close
browser.disconnect
```

```
#<Thread:0x00000001633b1d70 /Users/username/.rvm/gems/ruby-3.3.4/gems/puppeteer-ruby-0.45.6/lib/puppeteer/web_socket.rb:67 run> terminated with exception (report_on_exception is true):
/Users/username/.rvm/gems/ruby-3.3.4/gems/puppeteer-ruby-0.45.6/lib/puppeteer/web_socket.rb:44:in `readpartial': stream closed in another thread (IOError)
        from /Users/username/.rvm/gems/ruby-3.3.4/gems/puppeteer-ruby-0.45.6/lib/puppeteer/web_socket.rb:44:in `readpartial'
        from /Users/username/.rvm/gems/ruby-3.3.4/gems/puppeteer-ruby-0.45.6/lib/puppeteer/web_socket.rb:101:in `wait_for_data'
        from /Users/username/.rvm/gems/ruby-3.3.4/gems/puppeteer-ruby-0.45.6/lib/puppeteer/web_socket.rb:68:in `block in initialize'
```

### Expected behavior
No errors

### Environment
Ruby 3.3.4
Chrome for Testing Mac ARM 127.0.6533.119
MacBook Pro Apple M2 Pro
MacOS Sonoma 14.7

**Comment by ilyazub** [comment]
This issue is still actual. 

Related to https://github.com/YusukeIwaki/puppeteer-ruby/issues/319.
