### ISSUE TITLE
Connecting over websockets (browserless.io)

### ISSUE THREAD

**Issue by igorski89** [YusukeIwaki/puppeteer-ruby#94]
### Step To Reproduce / Observed behavior

Dear @YusukeIwaki ,

Thank you for all the hard work put into this project!

I am trying to connect to a browser over a websocket for testing purposes using browserless.io:

```ruby
require 'puppeteer'
require 'pathname'

Puppeteer.connect({
  browser_ws_endpoint: 'wss://chrome.browserless.io?token=REDACTED'
}) do |browser|
  await page.goto('chrome://gpu/')
  await page.screenshot(type:'png', path:File.join(Dir.getwd,"screenshot-#{Time.now.to_i}.png"), full_page: true)
end
```

However unfortunately the code crashes with following error:

```
$ ruby main.rb 
Traceback (most recent call last):
	12: from main.rb:4:in `<main>'
	11: from /Users/igorievsiukov/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.30.0/lib/puppeteer.rb:73:in `method_missing'
	10: from /Users/igorievsiukov/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.30.0/lib/puppeteer.rb:73:in `public_send'
	 9: from /Users/igorievsiukov/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.30.0/lib/puppeteer.rb:178:in `connect'
	 8: from /Users/igorievsiukov/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.30.0/lib/puppeteer/launcher/chrome.rb:159:in `connect'
	 7: from /Users/igorievsiukov/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.30.0/lib/puppeteer/launcher/chrome.rb:183:in `connect_with_browser_ws_endpoint'
	 6: from /Users/igorievsiukov/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.30.0/lib/puppeteer/web_socket_transport.rb:5:in `create'
	 5: from /Users/igorievsiukov/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.30.0/lib/puppeteer/web_socket_transport.rb:5:in `new'
	 4: from /Users/igorievsiukov/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.30.0/lib/puppeteer/web_socket.rb:36:in `initialize'
	 3: from /Users/igorievsiukov/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.30.0/lib/puppeteer/web_socket.rb:36:in `new'
	 2: from /Users/igorievsiukov/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.30.0/lib/puppeteer/web_socket.rb:12:in `initialize'
	 1: from /Users/igorievsiukov/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.30.0/lib/puppeteer/web_socket.rb:12:in `new'
/Users/igorievsiukov/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.30.0/lib/puppeteer/web_socket.rb:12:in `initialize': Can't assign requested address - connect(2) for "chrome.browserless.io" port  (Errno::EADDRNOTAVAIL)
```

### Expected behavior

Puppeteer connects to a remote instance and operates the same as with Chrome locally.

Similar code with Node.JS Puppeteer works without issues:

```javascript
const puppeteer = require('puppeteer');
const readline = require('readline');
const path = require('path');

const main = async () => {
  const browser = await puppeteer.connect({
    browserWSEndpoint: 'wss://chrome.browserless.io?token=REDACTED'
  });

  const page = await browser.newPage();
  await page.goto('chrome://gpu/');
  await page.screenshot({path: `screenshot-${Math.floor((new Date()).getTime()/1000)}.png`,fullPage:true});
}

main().then(console.log).catch(console.error);
```

I am happy to share the browserless token in DM for testing purposes if needed.

I do not have yet a deep knowledge of Ruby, maybe you can point me out to potential debugging or solution approaches?

Thank you very much in advance!

### Environment

Paste the output of `ruby --version`

```
$ ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]
```

**Comment by YusukeIwaki** [comment]
@igorski89 Thank you for your kind report. This issue is caused by 2 reason.

* No default port number for `wss`
  * Actually avoidable by specifying `:443` explicitly
* No logic for handling `wss` (SSL)
  * No workaround for this issue

I will create a new version of puppeteer-ruby for solving this.

**Comment by YusukeIwaki** [comment]
Puppeteer 0.32.1 would fix this issue.
Also I added an example for browserless.io https://github.com/YusukeIwaki/puppeteer-ruby-example/blob/master/7.with_browserless.io.rb

**Comment by igorski89** [comment]
Dear @YusukeIwaki  I am humbled by your support and all the work you are putting into this project. Thank you very much for resolving this issue, everything works great!
